defmodule Lincoln.Goals.Decomposer do
  @moduledoc """
  HTN-style goal decomposition with LLM assistance and a persistent method
  library.

  Pipeline for `decompose/2`:

    1. Compute embedding for the goal statement
    2. Look up a similar prior method (`MethodLibrary.find_similar/3`)
       - If found, instantiate sub-goals from its templates
       - If not, ask the LLM for a fresh decomposition, persist it as a
         new method, then instantiate sub-goals
    3. Insert sub-goals as children of the original goal with origin
       `"decomposed"`

  This means the *first* time Lincoln sees a kind of goal it spends LLM
  budget; every subsequent similar goal reuses the cached method. That is
  the GPT-HTN pattern in compact form.
  """

  alias Lincoln.{Goals, PubSubBroadcaster}
  alias Lincoln.Goals.{Goal, Method, MethodLibrary}

  require Logger

  @default_min_subgoals 1
  @default_max_subgoals 8

  @doc """
  Decompose a goal into sub-goals. Returns `{:ok, sub_goals}` on success,
  or `{:error, reason}` if no decomposition could be produced. A previously
  decomposed goal is left untouched (idempotent — caller should check
  `Goals.list_sub_goals/1` first if they want to know whether decomposition
  has already happened).
  """
  def decompose(%Goal{} = goal, opts \\ []) do
    embeddings = embeddings_adapter(opts)
    llm = llm_adapter(opts)
    agent = Lincoln.Agents.get_agent!(goal.agent_id)

    with {:ok, embedding} <- embed_or_skip(embeddings, goal),
         {:ok, templates, source} <-
           obtain_templates(agent, goal, embedding, llm, opts),
         {:ok, sub_goals} <- create_sub_goals(agent, goal, templates) do
      Logger.info(
        "[Decomposer] Decomposed '#{goal.statement}' into #{length(sub_goals)} sub-goals (source: #{source})"
      )

      Enum.each(sub_goals, &PubSubBroadcaster.broadcast_goal_created(agent.id, &1))

      {:ok, sub_goals}
    end
  end

  defp obtain_templates(agent, goal, embedding, llm, opts) do
    case embedding && MethodLibrary.find_similar(agent, embedding, opts) do
      %Method{sub_goal_templates: templates} = method
      when is_list(templates) and templates != [] ->
        {:ok, templates, {:cached, method.id}}

      _ ->
        case generate_with_llm(goal, llm, opts) do
          {:ok, templates} ->
            maybe_persist_method(agent, goal, templates, embedding)
            {:ok, templates, :llm}

          err ->
            err
        end
    end
  end

  defp generate_with_llm(goal, llm, opts) do
    min_n = Keyword.get(opts, :min_subgoals, @default_min_subgoals)
    max_n = Keyword.get(opts, :max_subgoals, @default_max_subgoals)

    prompt = """
    You are decomposing a goal into ordered sub-goals Lincoln can pursue.
    Goal: #{goal.statement}
    Priority: #{goal.priority}/10
    Deadline: #{format_deadline(goal.deadline)}

    Produce between #{min_n} and #{max_n} concrete, executable sub-goals
    that together accomplish the parent goal. Each sub-goal needs a
    "statement" and a "priority" (1-10).

    Return JSON:
    {
      "sub_goals": [
        {"statement": "First step", "priority": 7},
        {"statement": "Second step", "priority": 6}
      ]
    }
    """

    case llm.extract(prompt, %{type: "object"}, []) do
      {:ok, %{"sub_goals" => list}} when is_list(list) ->
        templates =
          list
          |> Enum.flat_map(&template_from/1)
          |> Enum.take(max_n)

        if length(templates) >= min_n do
          {:ok, templates}
        else
          {:error, :insufficient_subgoals}
        end

      {:ok, _} ->
        {:error, :unexpected_llm_shape}

      err ->
        err
    end
  rescue
    e ->
      Logger.warning("[Decomposer] LLM call failed: #{Exception.message(e)}")
      {:error, :llm_failed}
  end

  defp template_from(%{"statement" => statement} = m)
       when is_binary(statement) and statement != "" do
    [
      %{
        "statement" => statement,
        "priority" => Map.get(m, "priority", 5)
      }
    ]
  end

  defp template_from(_), do: []

  defp maybe_persist_method(_agent, _goal, _templates, nil), do: :ok

  defp maybe_persist_method(agent, goal, templates, embedding) do
    case MethodLibrary.record(
           agent,
           pattern_for(goal),
           templates,
           embedding,
           description: "Generated by LLM for goal: #{String.slice(goal.statement, 0, 200)}"
         ) do
      {:ok, _method} ->
        :ok

      {:error, changeset} ->
        Logger.warning("[Decomposer] Could not persist method: #{inspect(changeset.errors)}")
        :ok
    end
  end

  defp pattern_for(%Goal{statement: stmt}) do
    stmt
    |> String.downcase()
    |> String.replace(~r/[^a-z0-9 ]/, "")
    |> String.split()
    |> Enum.take(8)
    |> Enum.join("_")
  end

  defp create_sub_goals(_agent, _parent, []), do: {:ok, []}

  defp create_sub_goals(agent, parent, templates) do
    results =
      Enum.map(templates, fn template ->
        attrs = %{
          statement: Map.get(template, "statement") || Map.get(template, :statement),
          priority: Map.get(template, "priority") || Map.get(template, :priority) || 5,
          parent_goal_id: parent.id,
          origin: "decomposed"
        }

        Goals.create_goal(agent, attrs)
      end)

    case Enum.split_with(results, &match?({:ok, _}, &1)) do
      {oks, []} ->
        {:ok, Enum.map(oks, fn {:ok, g} -> g end)}

      {oks, errors} ->
        Logger.warning(
          "[Decomposer] #{length(errors)} sub-goals rejected, #{length(oks)} created"
        )

        {:ok, Enum.map(oks, fn {:ok, g} -> g end)}
    end
  end

  defp embed_or_skip(adapter, %Goal{statement: stmt}) when is_binary(stmt) do
    case adapter.embed(stmt, []) do
      {:ok, embedding} -> {:ok, embedding}
      _ -> {:ok, nil}
    end
  rescue
    _ -> {:ok, nil}
  end

  defp format_deadline(nil), do: "no deadline"
  defp format_deadline(%DateTime{} = dt), do: DateTime.to_string(dt)

  defp llm_adapter(opts) do
    Keyword.get(opts, :llm) ||
      Application.get_env(:lincoln, :llm_adapter, Lincoln.Adapters.LLM.Anthropic)
  end

  defp embeddings_adapter(opts) do
    Keyword.get(opts, :embeddings) ||
      Application.get_env(
        :lincoln,
        :embeddings_adapter,
        Lincoln.Adapters.Embeddings.PythonService
      )
  end
end
