defmodule Lincoln.Goals.Goal do
  @moduledoc """
  A goal Lincoln is pursuing.

  Goals are first-class entities — they have priority, deadline, success
  criteria, and a decomposition tree (parent / sub_goals). Goals integrate with
  the belief system by feeding `:goal_pursuit` impulses into Attention scoring.

  Status lifecycle:

    * `"active"` — currently being pursued
    * `"blocked"` — waiting on something external (paused, may resume)
    * `"achieved"` — success criteria met
    * `"abandoned"` — explicitly given up
    * `"pending_user_approval"` — self-proposed, awaiting human green-light

  Origin values:

    * `"user"` — created by a human via the API/UI
    * `"self"` — self-proposed by Lincoln (Phase 7+)
    * `"decomposed"` — generated by HTN decomposition from a parent goal

  `success_criteria` is a structured map — Phase 4 stores it but does not yet
  evaluate it; Phase 5+ goal pursuit threads will check it against beliefs and
  observations.
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  @statuses ~w(active blocked achieved abandoned pending_user_approval)
  @origins ~w(user self decomposed)

  schema "goals" do
    field :statement, :string
    field :status, :string, default: "active"
    field :priority, :integer, default: 5
    field :deadline, :utc_datetime
    field :origin, :string, default: "user"
    field :success_criteria, :map, default: %{}
    field :embedding, Pgvector.Ecto.Vector
    field :progress_estimate, :float, default: 0.0
    field :last_evaluated_at, :utc_datetime

    belongs_to :agent, Lincoln.Agents.Agent
    belongs_to :parent_goal, __MODULE__, foreign_key: :parent_goal_id
    has_many :sub_goals, __MODULE__, foreign_key: :parent_goal_id

    timestamps(type: :utc_datetime)
  end

  def statuses, do: @statuses
  def origins, do: @origins

  @doc false
  def changeset(goal, attrs) do
    goal
    |> cast(attrs, [
      :statement,
      :status,
      :priority,
      :deadline,
      :origin,
      :success_criteria,
      :embedding,
      :progress_estimate,
      :last_evaluated_at,
      :parent_goal_id
    ])
    |> validate_required([:statement])
    |> validate_inclusion(:status, @statuses)
    |> validate_inclusion(:origin, @origins)
    |> validate_number(:priority, greater_than_or_equal_to: 1, less_than_or_equal_to: 10)
    |> validate_number(:progress_estimate,
      greater_than_or_equal_to: 0.0,
      less_than_or_equal_to: 1.0
    )
  end

  @doc """
  Changeset for inserting a goal owned by an agent.
  """
  def create_changeset(goal, attrs, agent_id) do
    goal
    |> changeset(attrs)
    |> put_change(:agent_id, agent_id)
  end

  @doc """
  Changeset to record progress evaluation. Sets `last_evaluated_at` and the
  optional new estimate.
  """
  def progress_changeset(goal, progress_estimate) when is_number(progress_estimate) do
    goal
    |> change(
      progress_estimate: progress_estimate * 1.0,
      last_evaluated_at: DateTime.utc_now() |> DateTime.truncate(:second)
    )
  end
end
