defmodule Lincoln.Repo.Migrations.CreateQuestions do
  use Ecto.Migration

  def change do
    create table(:questions, primary_key: false) do
      add(:id, :binary_id, primary_key: true)
      add(:agent_id, references(:agents, type: :binary_id, on_delete: :delete_all), null: false)

      # Question content
      add(:question, :text, null: false)
      # What prompted this question
      add(:context, :text)

      # Semantic embedding for deduplication and clustering
      add(:embedding, :vector, size: 384)

      # Semantic hash for quick loop detection
      # Generated by hashing the embedding to detect near-duplicate questions
      add(:semantic_hash, :string)

      # Question lifecycle
      # :open - actively seeking answer
      # :answered - resolved with a finding
      # :abandoned - no longer pursuing
      # :merged - combined with another question
      add(:status, :string, default: "open")

      # Resolution tracking
      add(:resolved_at, :utc_datetime)
      add(:resolved_by_finding_id, :binary_id)

      # Priority and scheduling
      # 1-10
      add(:priority, :integer, default: 5)
      # For scheduling investigation
      add(:investigate_after, :utc_datetime)

      # Loop detection
      add(:times_asked, :integer, default: 1)
      add(:last_asked_at, :utc_datetime)

      # Cluster membership (for grouping similar questions)
      add(:cluster_id, :binary_id)

      timestamps(type: :utc_datetime)
    end

    create(index(:questions, [:agent_id]))
    create(index(:questions, [:status]))
    create(index(:questions, [:semantic_hash]))
    create(index(:questions, [:priority]))
    create(index(:questions, [:investigate_after]))
    create(index(:questions, [:cluster_id]))

    # Vector similarity index
    execute(
      "CREATE INDEX questions_embedding_idx ON questions USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)",
      "DROP INDEX IF EXISTS questions_embedding_idx"
    )
  end
end
